### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by Amyukxx** [BluebirdYT/Colorful-Trims#1]
Hi im getting this error in my console saying this 
Couldn't load tag minecraft:trim_materials as it is missing following references: #c:dyes (from file/colorful-trims-datapack)

**Comment by BluebirdYT** [comment]
Does everything still work as it should? Are you able to use dyes in the smithing table?

**Comment by Amyukxx** [comment]
no the hole thing stoped working i had to unstall it all

**Comment by BluebirdYT** [comment]
I fixed the issue so you can try again if you want

**Comment by Amyukxx** [comment]
Thank you..... :D
