### ISSUE TITLE
the datapack does not work on a vanilla realms server

### ISSUE THREAD

**Issue by curiouscarl** [BluebirdYT/Colorful-Trims#7]
screenshots can be found here:
https://imgur.com/a/colorful-trims-minecraft-realms-datapack-not-working-BdHFJaU
the datapack is somewhat working because i can place the yellow dye on the smithing table but i can't apply the trims.
if the datapack wasn't enabled, i couldn't even place it in that slot.

**Comment by BluebirdYT** [comment]
After you enable the datapack you have to restart the server in order for it to work.

**Comment by curiouscarl** [comment]
i dont know how, i dont know why but when hosting the world in a "non-Realms" server, the datapack worked correctly. i guess it wasn't the pack's fault.
